# Generated by Django 6.0.4 on 2026-05-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_invitecode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='student_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_codes', to='api.studentapplication'),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='tutor_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_codes', to='api.tutorapplication'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='contact_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='preferred_contact_method',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='contact_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tutorapplication',
            name='preferred_contact_method',
            field=models.CharField(default='Email', max_length=50),
        ),
    ]
