# Generated by Django 6.0.4 on 2026-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_invitecode_student_application_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttutorassignment',
            options={'verbose_name': 'Student-Tutor Assignment', 'verbose_name_plural': 'Student-Tutor Assignments'},
        ),
        migrations.RemoveConstraint(
            model_name='studenttutorassignment',
            name='unique_active_assignment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', to='api.profile'),
        ),
    ]
