# Generated by Django 6.0.4 on 2026-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_globalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
