# Generated by Django 6.0.4 on 2026-06-03 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_globalsetting_telegram_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='student_whatsapp_group_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='student_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='student_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='student_marked_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_confirmed_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tutor_marked_held',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.course')),
            ],
        ),
    ]
